config/routes.rb
Rails.application.routes.draw do
  get '/users', to: 'users#index', as: 'users'
  get '/users/:id', to: 'users#show', as: 'user'
  get '/users/:user_id/posts', to: 'posts#index', as: 'user_posts'
  get '/users/:user_id/posts/:id', to: 'posts#show', as: 'user_post'
  get '/users', to: 'users#index', as: 'users_index'

  get '/posts', to: 'posts#index', as: 'posts_index'

  get '/posts/:id', to: 'posts#show', as: 'post'

  # get '/users/:id', to: 'users#show', as: 'user'

  # get '/users', to: 'users#index', as: 'users_index'

# get '/users/:id', to: 'users#show', as: 'user'
end

app/models/application_record.rb
# rubocop:disable all
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/mynewcomment_new.rb
#rubocop:disable all
# app/models/mynewcomment_new.rb

class MynewcommentNew < ApplicationRecord
  self.table_name = 'mynewcomments'

  belongs_to :author, class_name: 'User', foreign_key: 'user_id'
  belongs_to :post, class_name: 'MynewpostNew'

  attribute :text, :text

  after_create :update_comment_counter
  after_destroy :update_comment_counter

  attr_accessor :CommentsCounter

  def update_comment_counter
    post.update(comment_counter: post.comments.count)
  end
end
#   MynewcommentNew.create(post: first_post, author: second_user, text: 'Hi Tom!' )

# first_user = User.create(name: 'dsafs', email: 'dsafa@gmail.com', password_digest: '7667')

app/models/mynewlikes_new.rb
class MynewlikesNew < ApplicationRecord
  self.table_name = 'mynewlikes'

  belongs_to :user, class_name: 'User'
  belongs_to :post, class_name: 'MynewpostNew'

  after_save :update_like_counter

  def update_like_counter
    post.update(like_counter: post.likes.count)
  end
end

app/models/mynewpost_new.rb
class MynewpostNew < ApplicationRecord
  self.table_name = 'mynewposts'

  validates :title, presence: true, length: { maximum: 250 }
  validates :comment_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :like_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  has_many :comments
  has_many :likes

  attribute :title, :string
  attribute :text, :text
  attribute :comment_counter, :integer, default: 0
  attribute :like_counter, :integer, default: 0

  after_save :update_post_counter

  def update_post_counter
    author.update(post_counter: author.posts.count)
  end

  def recent_comments
    comments.order(created_at: :desc).limit(5)
  end
end

# first_post = MynewpostNew.create(author_id: first_user.id, title: 'Hello', text: 'This is my first post')

app/models/user.rb
class User < ApplicationRecord
  self.table_name = 'myusers'

  has_secure_password

  validates :name, presence: true

  validates :post_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  has_many :posts, foreign_key: :author_id
  has_many :comments
  has_many :likes

  attribute :name, :string
  attribute :bio, :text
  attribute :post_counter, :integer, default: 0
  attribute :photo, :string

  def recent_posts
    posts.order(created_at: :desc).limit(3)
  end
end

app/controllers/application_controller.rb
# rubocop:disable all
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @user = User.find(params[:user_id])
    @posts = @user.posts.includes(:comments)
  end

  def show
    @post = Post.includes(:comments).find(params[:id])
    @user = User.find(params[:user_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts
  end
end

app/helpers/application_helper.rb
# rubocop:disable all
module ApplicationHelper
end

app/helpers/posts_helper.rb
# rubocop:disable all
module PostsHelper
end

app/helpers/users_helper.rb
# rubocop:disable all
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GemWebBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<section class="container">
<article class="users-article">
<div class="photo"><%= @user.photo %></div>
<div class="details">
 <h2><%= @user.name %></h2>
  <p>Total post: <%= @user.posts_counter %></p>
</div>
</article>

<% @posts.each do |post| %>
    <article class="post-comment">
    <div class="posts-details">
  <h2><%= link_to "Post ", user_post_url(@user.id, post.id) %> #<%= post.id %></h2>
  <h3><%= post.text %></h3>
  <p>Comments:<%= post.comments_counter %>,Likes:<%= post.likes_counter %></p>
  </div>

  <div class="comment-cont">
  <% post.recent_comments.each do |comment| %>
    <p><%= @user.name %>: <%= comment.text %> <%= comment.id %></p>
    <% end %>
  </div>
  
  </article>
  <% end %>
    <button type="button" class="pagination">Pagination</button>
</section>

app/views/posts/show.html.erb
<section class="post-container">
<article class="post-comments">
<div class="post-head">
  <div class="left">
    <h4>Post  #<%= @post.id %><h4>
    <p>by <%= @user.name %></p>
 </div>
 <div>
<span>Comment: <%= @post.comments_counter %> Likes:<%= @post.likes_counter %></span>
</div>
</div>
<div class="post-body">
<h4><%= @post.text %></h4>
</div>

</article>
<div class="comments-container">
<% @post.comments.each do |comment| %>
    <p><%= comment.user.name %>: <%= comment.text %> <%= comment.id %></P>
    <% end %>
</div>

</section>

app/views/users/_user_info.html.erb
<article class="users-article">
<div class="photo"><%= user.photo %></div>
<div class="details">
 <h2><%= link_to user.name, user_url(user.id) %></h2>
  <p>Total posts: <%= user.posts_counter %></p>
</div>
</article>

app/views/users/index.html.erb
<section class="container">
  <% @users.each do |user| %>
    <%= render partial: 'user_info', locals: { user: user } %>
  <% end %>
</section>

app/views/users/show.html.erb
<section class="container">
<article class="users-article">
<div class="photo"><%= @user.photo %></div>
<div class="details">
 <h2><%= @user.name %></h2>
  <p><%= link_to "Number of posts:", user_posts_url(@user.id) %> <%= @user.posts_counter %></p>
</div>
</article>
<div class="bio">
  <p>Bio</p>
  <p><%= @user.bio %></p>
</div>
    <% @user.recent_posts.each do |post| %>
        <div class="post-details">
      <h2><%= link_to "Post #", user_post_url(@user.id, post.id) %><%= post.id %></h2>
      <h3><%= post.text %></h3>
      <p>Comments:<%= post.comments_counter %>,Likes:<%= post.likes_counter %></p>
      </div>
    <% end %>
    <%= link_to user_posts_path(@user.id) do %>
    <button type="button" class="see-posts">See all posts</button>
    <% end %>
</section>